declare const PACKAGE_ROOT: string;
/** Pixel Guard package root (output/ when published, repo root in dev). */
export { PACKAGE_ROOT };
export declare function getBundledComponentInventoryTemplatePath(): string;
/**
 * Workspace root for generated artifacts (page comparisons, playwright reports).
 * Set via MCP config env PROJECT_ROOT — same pattern as ui-audit remote setup.
 */
export declare const PROJECT_ROOT: string;
/** @deprecated Use PROJECT_ROOT */
export declare const REPO_ROOT: string;
/** @deprecated Reports live directly under PROJECT_ROOT/<reportId>/ */
export declare const PAGE_COMPARE_REPORTS_DIR: string;
/** Report folder: PROJECT_ROOT/<reportId>/ */
export declare function getReportDir(reportId: string): string;
/** URL path prefix for serving a report over HTTP. */
export declare function getPageComparisonReportBasePath(reportId: string): string;
/** Playwright HTML report directory (generated by visual tests in the project). */
export declare const PLAYWRIGHT_REPORT_DIR: string;
export declare const PLAYWRIGHT_REPORT_INDEX: string;
/** Compiled UI bundle directory (output/ when built, package root when running via tsx). */
export declare const DIST_DIR: string;
export declare function getPageComparisonReportUrl(reportId: string, reportDir: string): string;
export declare function getReportArtifactUrl(reportId: string, reportDir: string, artifactFile: string): string;
