/** AEM / EDS site repo root (parent of mcp-apps/pixel-guard). */
export declare const REPO_ROOT: string;
/** Playwright HTML report directory (generated by `npm run test:visual:*` in the repo). */
export declare const PLAYWRIGHT_REPORT_DIR: string;
export declare const PLAYWRIGHT_REPORT_INDEX: string;
