export const PLAYWRIGHT_REPORT_RESOURCE_URI = 'ui://playwright-report';

const PLAYWRIGHT_REPORT_APP_HTML = `<!doctype html>
<html>
  <head>
    <style>
      html, body { margin: 0; padding: 0; height: 100%; font-family: system-ui, sans-serif; }
      #message { padding: 12px; color: #444; }
      iframe { width: 100%; height: 100%; border: 0; display: none; }
    </style>
  </head>
  <body>
    <div id="message">Waiting for visual test results&hellip;</div>
    <iframe id="report" title="Playwright report"></iframe>
    <script type="module">
      import { App } from 'https://cdn.jsdelivr.net/npm/@modelcontextprotocol/ext-apps/+esm';

      const app = new App({ name: 'Playwright Report Viewer', version: '1.0.0' });
      const messageEl = document.getElementById('message');
      const frameEl = document.getElementById('report');

      app.ontoolresult = (params) => {
        const data = (params && params.structuredContent) || {};
        if (data.reportUrl) {
          frameEl.src = data.reportUrl;
          frameEl.style.display = 'block';
          messageEl.style.display = 'none';
        } else {
          messageEl.textContent = data.message || 'No Playwright report was generated for this run.';
        }
      };

      await app.connect();
    </script>
  </body>
</html>`;

export const playwrightReportAppResources = {
  [PLAYWRIGHT_REPORT_RESOURCE_URI]: {
    name: 'Playwright Visual Test Report',
    description: 'Displays the HTML report generated by the most recent Playwright visual test run.',
    html: PLAYWRIGHT_REPORT_APP_HTML,
  },
};
